import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { cn } from "@/lib/utils";

const vazirmatn = localFont({
  src: [
    {
      path: "../assets/fonts/ttf/Vazirmatn-Black.ttf",
      weight: "400",
    },
    {
      path: "../assets/fonts/ttf/Vazirmatn-Bold.ttf",
      weight: "400",
    },
    {
      path: "../assets/fonts/ttf/Vazirmatn-ExtraBold.ttf",
      weight: "700",
    },
    {
      path: "../assets/fonts/ttf/Vazirmatn-ExtraLight.ttf",
      weight: "400",
    },
    {
      path: "../assets/fonts/ttf/Vazirmatn-Light.ttf",
      weight: "300",
    },
    {
      path: "../assets/fonts/ttf/Vazirmatn-Medium.ttf",
      weight: "300",
    },
    {
      path: "../assets/fonts/ttf/Vazirmatn-Regular.ttf",
      weight: "300",
    },
    {
      path: "../assets/fonts/ttf/Vazirmatn-SemiBold.ttf",
      weight: "300",
    },
    {
      path: "../assets/fonts/ttf/Vazirmatn-Thin.ttf",
      weight: "300",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body className={cn("bg-background", vazirmatn.className)}>
        <main className="mx-auto h-dvh min-h-dvh w-full max-w-sm">
          {children}
        </main>
      </body>
    </html>
  );
}
