export { Banners } from './banners';
export { BottomNavigation } from './bottom-navigation';
export { Categories } from './categories';
export { Comparetaion } from './comperation/comparetaion';
export { Favorites } from './favorites';
export { ResentViews } from './resent-views';
export { SearchAction } from './search-action';
export { TopSellers } from './top-sellers';
export { Category } from './category';
